#!/bin/bash
#
# Prep OCaml code to be compiled, removing directives
# and commenting out interactive examples.

echo "open Num;;"
echo "open Format;;"

cat $@ | sed -e 's/START_INTERACTIVE;;/(\*/' \
             -e 's/END_INTERACTIVE;;/\*)/'   \
	     -e '/#install_printer/d'
